# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bubble' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bubble
  pod "Firebase/Core"
  pod "Firebase/Firestore"
  pod "Firebase/Auth"
  pod "FacebookCore"
  pod "FacebookLogin"
  pod "GoogleSignIn"
  pod 'ARCL'
  pod "FirebaseStorage"

  target 'bubbleTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Firebase/Core"
    pod "Firebase/Firestore"
    pod "Firebase/Auth"
    pod "FacebookCore"
    pod "FacebookLogin"
    pod "GoogleSignIn"
    pod 'ARCL'  
  end

  target 'bubbleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
